---
- hosts: localhost
  connection: local
  tasks:
    - name: Pull the latest calculator image from Docker Hub
      docker_image:
        name: harsh2835/spe_mini_project:latest
        source: pull

    - name: Stop and remove the old calculator container if it exists
      docker_container:
        name: scientific-calculator
        state: absent

    - name: Run the new calculator container
      docker_container:
        name: scientific-calculator
        image: harsh2835/spe_mini_project:latest
        state: started
        interactive: yes
        tty: yes